### ISSUE TITLE
a bug about upgrade

### ISSUE THREAD

**Issue by S-Kee** [dcartertod/zotero-plugins#15]
No matter the version of the plugin, the plugin can upgrade.
![image](https://user-images.githubusercontent.com/21167731/158064015-581a171e-653b-4459-9987-47a27f4c364c.png)
![image](https://user-images.githubusercontent.com/21167731/158064030-4b3510ed-cbea-496d-a483-cf6717935ce2.png)

**Comment by dcartertod** [comment]
That's the most recent version

**Comment by S-Kee** [comment]
> That's the most recent version

I know it is the most recent version, but it still notice user to upgrade. When you upgraded, it still notice user upgrade again.

**Comment by welpdx** [comment]
I have the same issue too. When I "Check for Update" in Zotero, it keeps saying that ZoteroPreview has an update and I should update it again. 

I think it is to do with your install.rdf. If you change your Install.rdf line from 
` <em:updateURL>https://raw.githubusercontent.com/dcartertod/zotero-plugins/main/ZoteroPreview/zoteropreview-update.rdf</em:updateURL>`
 to 
`<em:updateURL>https://github.com/dcartertod/zotero-plugins/raw/main/ZoteroPreview.xpi</em:updateURL>`
 or even 
`<em:updateURL>https://github.com/dcartertod/zotero-plugins/releases/download/0.0.8/ZoteroPreview.xpi</em:updateURL>`
the problem is solved.

**Comment by dcartertod** [comment]
Yes, that's the issue. This should be resolved now.

**Comment by welpdx** [comment]
Yuup, can confirm problem solved!

**Comment by dcartertod** [comment]
Resolved.
