### ISSUE TITLE
Review icon and copy function

### ISSUE THREAD

**Issue by dcartertod** [dcartertod/zotero-plugins#29]
Check for icon set and copy function

**Comment by dcartertod** [comment]
icon fixed using svg. still researching copy issue. cannot reproduce

**Comment by omundy** [comment]
On Macbook Pro M1 with MacOS 13.6.3 ...
1. The "copy" icon does not initiate the pointer cursor on hover
2. The urls in the citation are shown in blue with underline and display the pointer on hover but clicking them does nothing
3. I'm not seeing any of the [logging](https://github.com/dcartertod/zotero-plugins/blob/73adc7a8ec9a90c3222e529a6b74307fa9335134/ZoteroPreview7/zoteropreview.js#L21) indicated in the source code in Tools > Developer > Error Console

Could you describe how I might build and test the XPI file locally? Is there something I can use to examine the rendered HTML elements like with DevTools in a regular browser?

**Comment by dcartertod** [comment]
1. I can try to make that happen. Not sure.
2. Not sure about that one
3. Look under Help > Debug Output Logging > Enable (and then View Output)

You can create a new profile for Zotero using the -p command line option, and also set it to show the console and debug output by default. On Windows for me, it looks like this:

`"C:\Program Files\Zotero\zotero.exe" -p Developer  -ZoteroDebugText -ZoteroDebug -purgecaches -jsconsole`

Although to be honest, it doesn't seem to work very consistently. [General instructions for development here](https://www.zotero.org/support/dev/zotero_7_for_developers). I get the sense that primary development is on Mac, so it may be easier for you. I've never been able to get the Firefox part of things working, but I've seen comments that it's much easier on a Mac.

To test "live" changes, you replace the extension in your profile extensions directory with a text file containing the path to your code. Then after making code edits, disable/re-enable the add-on or just restart Zotero (using the same debug menu).

I have never hung out on the dev list. I probably should. It's mostly been (a lot of) trial and error and looking at the source code on GitHub.

In the error console there are a lot of things in scope, but 

`Zotero.getActiveZoteroPane().document.getElementById('zotero-view-item-container');`

Is where I've spent a lot of time.

XPI files are just .zip files with the code in them. Nothing special. You can tell from my PowerShell script. The Make-it-red add-on from the Zotero repository has the Linux/Mac equivalent.

**Comment by dcartertod** [comment]
The copy mouse hover is now a pointer.

**Comment by omundy** [comment]
1. I can confirm clicking the copy icon works on Mac
2. I wouldn't worry about making this a working link. It's just kind of weird that it's blue and responds to mousedown but doesn't open the page in a browser.
3. I forked the repo and set up the developer profile and can see the messages. Thanks.
4. The preview icon looks great! However, there is an issue because it will only show the preview if you haven't edited the preference. Once you change the Position preference it will not expand and show the preview. I double-checked this is the case by deleting the preference and restarting, and it worked again.

![image](https://github.com/dcartertod/zotero-plugins/assets/279945/da117a72-9e6a-47cb-8890-6178dff36a58)

**Comment by dcartertod** [comment]
4. Sounds like a basic logic problem on my part. I'll look at that. I think I know what it is. I changed the id of the main container.

**Comment by dcartertod** [comment]
I think I've fixed it.

**Comment by omundy** [comment]
It works great. Thanks for all your work!

I submitted a small [PR](https://github.com/dcartertod/zotero-plugins/pull/31) so the icons are visible on light/dark modes. I picked the gold color because [it is part of the existing scheme](https://github.com/zotero/zotero/blob/b8fa54ecce0fac2e942fa2cc5f5316c81d30bdb6/scss/themes/_light.scss#L10) but [it isn't currently used by other sections](https://github.com/zotero/zotero/blob/b8fa54ecce0fac2e942fa2cc5f5316c81d30bdb6/scss/abstracts/_variables.scss#L83). I also changed the strings to uses template literals. I hope you don't mind. One you try them you'll never go back :-)

![image](https://github.com/dcartertod/zotero-plugins/assets/279945/6c2501d8-2601-465e-a74c-439fc65ec619)
![image](https://github.com/dcartertod/zotero-plugins/assets/279945/9b8b03eb-9d47-464a-b18f-1b5de5004e4c)

**Comment by dcartertod** [comment]
Thank you. I think I've accepted them correctly and have incorporated them. Released.
